youtubeApiKey: ''

queries:
  - name: bizarrap
    youtubeQuery:
      q: ''
      maxResults: 20
      channelId: 'UCmS75G-98QihSusY7NfCZtw' #
    checkInterval: 1 #minutes
    handler: queue
    filters:
      - id: filterByLength
        args:
          min: 0
          max: Infinity

  - name: funny-pitbulls
    youtubeQuery:
      q: 'pitbul funny cute'
      maxResults: 20
    checkInterval: 15 #minutes
    handler: queue
    filters:
      - id: filterByLength
        args:
          min: 0
          max: 20

queue:
  url: QUEUE_URL
